### PR TITLE
Make the page responsive and mobile-first

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Any screenshots? Not sure why we are not getting deploy previews here

**Comment by LeaVerou** [comment]
In addition to reducing padding & font size, it may help to lay out buttons vertically rather than next to each other

**Comment by DmitrySharabin** [comment]
@LeaVerou I made a video so you could see different stages on different screen sizes. I believe we can stick with the buttons in a row on small devices as well.

https://user-images.githubusercontent.com/9166277/222750519-e20840b1-0063-4443-aa02-46056f1cfa41.mp4

**Comment by LeaVerou** [comment]
Nice, thanks!

> I believe we can stick with the buttons in a row on small devices as well.

We could, but why? A button wrapped in 3 rows looks a bit odd.

**Comment by DmitrySharabin** [comment]
> We could, but why? A button wrapped in 3 rows looks a bit odd.

Oh. I should have quoted your previous comment (“...it may help to lay out buttons vertically rather than next to each other”) to be clear. Sorry about that. I meant there is enough room for both yes and no buttons in one row, so there is no need to lay them out vertically.

**Comment by DmitrySharabin** [comment]
Yes. Do you think we should lay them out vertically?

**Comment by LeaVerou** [comment]
Yes, I think so

**Comment by DmitrySharabin** [comment]
OK. Will do it.

**Comment by DmitrySharabin** [comment]
What version do you like more: v1 or v2? The difference is in the third “step”—“Mobile L – 425px.” I'll push the one we choose.

### v1

https://user-images.githubusercontent.com/9166277/222844332-88576a5d-fc05-4fa2-8768-04d2510a98ce.mp4


### v2

https://user-images.githubusercontent.com/9166277/222844366-c01443b9-02df-44a1-a448-d6feae189434.mp4

**Comment by LeaVerou** [comment]
Not sure, but both still have a version where you get a button with 3 rows. that should not happen

**Comment by DmitrySharabin** [comment]
> Not sure, but both still have a version where you get a button with 3 rows. That should not happen

Oh! Now I see what you meant by 3 rows. 🤦‍♂️ Agreed, that should not happen. Will fix it. Thanks!

**Comment by DmitrySharabin** [comment]
How about this one?


https://user-images.githubusercontent.com/9166277/222924213-a74e22a1-5e44-40a8-a94e-3a985cf2e562.mp4

**Comment by LeaVerou** [comment]
I think that works well. You could also add `text-wrap: balance` to the buttons for when it ships 😁

**Comment by DmitrySharabin** [comment]
> I think that works well. You could also add `text-wrap: balance` to the buttons for when it ships 😁

Excellent idea! 😁

**Pull request merged**
